spring:
  application:
    name: dance-club-backend

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

jwt:
  secret: ${JWT_SECRET}
  access-expiration: ${JWT_ACCESS_EXPIRATION:1800000}    # 30분 (ms)
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000} # 7일 (ms)

